channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - addict
  - click
  - deeptime
  - h5py
  - mdshare
  - mdtraj
  - numpy
  - pydash
  - pytest
  - setuptools
  - pytorch
  - tqdm
  - jupyterlab