device: cpu
estimator_type: batch
hidden_layer_width: 10
input_dim: 2
lag_time: 1
lr: 0.0005
n_epochs: 30
n_hidden_layers: 1
npz_dataset_path: data/processed/alanine-dipeptide-dihedrals/alanine-dipeptide-3x250ns-backbone-dihedrals.npz
optimizer: Adam
output_dim: 1
output_softmax: false
runner: VAMPnetEstimator
score:
  epsilon: 1.0e-06
  method: VAMP2
  mode: regularize
